#!/bin/bash

# Export Mailchimp tags to markdown file
# Change to parent directory to access shared config and secrets
cd "$(dirname "$0")/.."
source "shared-config.sh"

OUTPUT_FILE="mailchimp/mailchimp_tags.md"

echo "=== Exporting Mailchimp Tags to $OUTPUT_FILE ==="

# Create the markdown file
cat > "$OUTPUT_FILE" << 'EOF'
# Mailchimp Tags Export
## Generated: 
EOF

# Add current date
echo "$(date '+%Y-%m-%d %H:%M:%S')" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'

## All Tags

EOF

# Get all tags and format them
echo "Fetching all tags..."
all_tags_result=$(mailchimp_get_tags)

if [[ $? -eq 0 ]]; then
    echo "### Total Tags: $(echo "$all_tags_result" | grep -c '"name"')" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    # Create a table
    echo "| ID | Tag Name |" >> "$OUTPUT_FILE"
    echo "|---|---|" >> "$OUTPUT_FILE"
    
    # Parse and add each tag
    echo "$all_tags_result" | grep -o '"id":[0-9]*,"name":"[^"]*' | while IFS= read -r line; do
        id=$(echo "$line" | grep -o '"id":[0-9]*' | cut -d':' -f2)
        name=$(echo "$line" | grep -o '"name":"[^"]*' | cut -d'"' -f4)
        echo "| $id | $name |" >> "$OUTPUT_FILE"
    done
    
    echo "" >> "$OUTPUT_FILE"
    
    # Add family tags section
    echo "## Family Year Tags" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    family_tags_result=$(mailchimp_get_tags "family")
    if [[ $? -eq 0 ]]; then
        echo "### Family graduation year tags found:" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "| ID | Tag Name | Graduation Year |" >> "$OUTPUT_FILE"
        echo "|---|---|---|" >> "$OUTPUT_FILE"
        
        echo "$family_tags_result" | grep -o '"id":[0-9]*,"name":"family-[^"]*' | while IFS= read -r line; do
            id=$(echo "$line" | grep -o '"id":[0-9]*' | cut -d':' -f2)
            name=$(echo "$line" | grep -o '"name":"[^"]*' | cut -d'"' -f4)
            year=$(echo "$name" | grep -o '[0-9]\+$')
            echo "| $id | $name | 20$year |" >> "$OUTPUT_FILE"
        done
    fi
    
    echo "" >> "$OUTPUT_FILE"
    
    # Add segments section
    echo "## Segments (Tag-like Groups)" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    segments_result=$(mailchimp_get_segments)
    if [[ $? -eq 0 ]]; then
        echo "### Segments found:" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "| ID | Segment Name | Member Count | Type |" >> "$OUTPUT_FILE"
        echo "|---|---|---|---|" >> "$OUTPUT_FILE"
        
        echo "$segments_result" | grep -o '"id":[0-9]*,"name":"[^"]*","member_count":[0-9]*,"type":"[^"]*' | while IFS= read -r line; do
            id=$(echo "$line" | grep -o '"id":[0-9]*' | cut -d':' -f2)
            name=$(echo "$line" | grep -o '"name":"[^"]*' | cut -d'"' -f4)
            count=$(echo "$line" | grep -o '"member_count":[0-9]*' | cut -d':' -f2)
            type=$(echo "$line" | grep -o '"type":"[^"]*' | cut -d'"' -f4)
            echo "| $id | $name | $count | $type |" >> "$OUTPUT_FILE"
        done
    fi
    
    echo "" >> "$OUTPUT_FILE"
    
    # Add interest groups section
    echo "## Interest Groups" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    interest_result=$(mailchimp_get_interest_categories)
    if [[ $? -eq 0 ]]; then
        echo "### Interest Categories:" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        
        echo "$interest_result" | grep -o '"id":"[^"]*","title":"[^"]*' | while IFS= read -r line; do
            category_id=$(echo "$line" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
            category_title=$(echo "$line" | grep -o '"title":"[^"]*' | cut -d'"' -f4)
            
            echo "#### $category_title (ID: $category_id)" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            
            # Get interests for this category
            interests_result=$(mailchimp_get_interests "$category_id" 2>/dev/null)
            if [[ $? -eq 0 ]]; then
                echo "| Interest ID | Interest Name |" >> "$OUTPUT_FILE"
                echo "|---|---|" >> "$OUTPUT_FILE"
                
                echo "$interests_result" | grep -o '"id":"[^"]*","name":"[^"]*' | while IFS= read -r interest_line; do
                    interest_id=$(echo "$interest_line" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
                    interest_name=$(echo "$interest_line" | grep -o '"name":"[^"]*' | cut -d'"' -f4)
                    echo "| $interest_id | $interest_name |" >> "$OUTPUT_FILE"
                done
            fi
            echo "" >> "$OUTPUT_FILE"
        done
    fi
    
    # Add footer
    cat >> "$OUTPUT_FILE" << 'EOF'

---
*Generated by GAM Mailchimp integration scripts*
EOF
    
    echo "✅ Successfully exported tags to $OUTPUT_FILE"
    echo "📁 File location: $(pwd)/$OUTPUT_FILE"
    
else
    echo "❌ Failed to fetch Mailchimp tags"
    exit 1
fi